// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpc.proto
// Protobuf C++ Version: 5.27.2

#include "rpc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace masterSlaveRPC {

inline constexpr NodeMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : nodename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NodeMessage::NodeMessage(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct NodeMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NodeMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NodeMessageDefaultTypeInternal() {}
  union {
    NodeMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NodeMessageDefaultTypeInternal _NodeMessage_default_instance_;

inline constexpr MapDataList::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filename_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MapDataList::MapDataList(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MapDataListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MapDataListDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MapDataListDefaultTypeInternal() {}
  union {
    MapDataList _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MapDataListDefaultTypeInternal _MapDataList_default_instance_;

inline constexpr Id::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : taskid_{0u},
        jobid_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Id::Id(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct IdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IdDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IdDefaultTypeInternal() {}
  union {
    Id _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IdDefaultTypeInternal _Id_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR EventMessage::EventMessage(::_pbi::ConstantInitialized) {}
struct EventMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventMessageDefaultTypeInternal() {}
  union {
    EventMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventMessageDefaultTypeInternal _EventMessage_default_instance_;

inline constexpr JobMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{nullptr},
        type_{static_cast< ::masterSlaveRPC::TaskType >(0)},
        jobnum_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR JobMessage::JobMessage(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct JobMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JobMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JobMessageDefaultTypeInternal() {}
  union {
    JobMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JobMessageDefaultTypeInternal _JobMessage_default_instance_;
}  // namespace masterSlaveRPC
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_rpc_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_rpc_2eproto = nullptr;
const ::uint32_t
    TableStruct_rpc_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::NodeMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::NodeMessage, _impl_.nodename_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::Id, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::Id, _impl_.taskid_),
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::Id, _impl_.jobid_),
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::JobMessage, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::JobMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::JobMessage, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::JobMessage, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::JobMessage, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::JobMessage, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::JobMessage, _impl_.jobnum_),
        ~0u,
        ~0u,
        ~0u,
        0,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::MapDataList, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::MapDataList, _impl_.filename_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::EventMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::masterSlaveRPC::NodeMessage)},
        {9, -1, -1, sizeof(::masterSlaveRPC::Id)},
        {19, 32, -1, sizeof(::masterSlaveRPC::JobMessage)},
        {37, -1, -1, sizeof(::masterSlaveRPC::MapDataList)},
        {46, -1, -1, sizeof(::masterSlaveRPC::EventMessage)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::masterSlaveRPC::_NodeMessage_default_instance_._instance,
    &::masterSlaveRPC::_Id_default_instance_._instance,
    &::masterSlaveRPC::_JobMessage_default_instance_._instance,
    &::masterSlaveRPC::_MapDataList_default_instance_._instance,
    &::masterSlaveRPC::_EventMessage_default_instance_._instance,
};
const char descriptor_table_protodef_rpc_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\trpc.proto\022\016masterSlaveRPC\032\033google/prot"
    "obuf/empty.proto\"\037\n\013NodeMessage\022\020\n\010nodeN"
    "ame\030\001 \001(\t\"#\n\002Id\022\016\n\006taskId\030\001 \001(\r\022\r\n\005jobId"
    "\030\002 \001(\r\"\200\001\n\nJobMessage\022&\n\004type\030\001 \001(\0162\030.ma"
    "sterSlaveRPC.TaskType\022\013\n\003key\030\002 \001(\t\022\r\n\005va"
    "lue\030\003 \001(\t\022\036\n\002id\030\004 \001(\0132\022.masterSlaveRPC.I"
    "d\022\016\n\006jobnum\030\005 \001(\r\"\037\n\013MapDataList\022\020\n\010file"
    "name\030\001 \003(\t\"\016\n\014EventMessage**\n\010TaskType\022\007"
    "\n\003map\020\000\022\n\n\006reduce\020\001\022\t\n\005fetch\020\0022\365\002\n\006JobRp"
    "c\022G\n\nRequireJob\022\033.masterSlaveRPC.NodeMes"
    "sage\032\032.masterSlaveRPC.JobMessage\"\000\022N\n\020Fe"
    "tchDataFromMap\022\033.masterSlaveRPC.NodeMess"
    "age\032\033.masterSlaveRPC.MapDataList\"\000\022G\n\017Re"
    "portJobStatus\022\032.masterSlaveRPC.JobMessag"
    "e\032\026.google.protobuf.Empty\"\000\022E\n\013ReportEve"
    "nt\022\034.masterSlaveRPC.EventMessage\032\026.googl"
    "e.protobuf.Empty\"\000\022B\n\tHeartBeat\022\033.master"
    "SlaveRPC.NodeMessage\032\026.google.protobuf.E"
    "mpty\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_rpc_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_rpc_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rpc_2eproto = {
    false,
    false,
    734,
    descriptor_table_protodef_rpc_2eproto,
    "rpc.proto",
    &descriptor_table_rpc_2eproto_once,
    descriptor_table_rpc_2eproto_deps,
    1,
    5,
    schemas,
    file_default_instances,
    TableStruct_rpc_2eproto::offsets,
    file_level_enum_descriptors_rpc_2eproto,
    file_level_service_descriptors_rpc_2eproto,
};
namespace masterSlaveRPC {
const ::google::protobuf::EnumDescriptor* TaskType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_rpc_2eproto);
  return file_level_enum_descriptors_rpc_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t TaskType_internal_data_[] = {
    196608u, 0u, };
bool TaskType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// ===================================================================

class NodeMessage::_Internal {
 public:
};

NodeMessage::NodeMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:masterSlaveRPC.NodeMessage)
}
inline PROTOBUF_NDEBUG_INLINE NodeMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::masterSlaveRPC::NodeMessage& from_msg)
      : nodename_(arena, from.nodename_),
        _cached_size_{0} {}

NodeMessage::NodeMessage(
    ::google::protobuf::Arena* arena,
    const NodeMessage& from)
    : ::google::protobuf::Message(arena) {
  NodeMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:masterSlaveRPC.NodeMessage)
}
inline PROTOBUF_NDEBUG_INLINE NodeMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : nodename_(arena),
        _cached_size_{0} {}

inline void NodeMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
NodeMessage::~NodeMessage() {
  // @@protoc_insertion_point(destructor:masterSlaveRPC.NodeMessage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NodeMessage::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.nodename_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
NodeMessage::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(NodeMessage, _impl_._cached_size_),
              false,
          },
          &NodeMessage::MergeImpl,
          &NodeMessage::kDescriptorMethods,
          &descriptor_table_rpc_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 43, 2> NodeMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_NodeMessage_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::masterSlaveRPC::NodeMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string nodeName = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NodeMessage, _impl_.nodename_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string nodeName = 1;
    {PROTOBUF_FIELD_OFFSET(NodeMessage, _impl_.nodename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\10\0\0\0\0\0\0"
    "masterSlaveRPC.NodeMessage"
    "nodeName"
  }},
};

PROTOBUF_NOINLINE void NodeMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:masterSlaveRPC.NodeMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nodename_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* NodeMessage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:masterSlaveRPC.NodeMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string nodeName = 1;
  if (!this->_internal_nodename().empty()) {
    const std::string& _s = this->_internal_nodename();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "masterSlaveRPC.NodeMessage.nodeName");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:masterSlaveRPC.NodeMessage)
  return target;
}

::size_t NodeMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:masterSlaveRPC.NodeMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string nodeName = 1;
  if (!this->_internal_nodename().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_nodename());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void NodeMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NodeMessage*>(&to_msg);
  auto& from = static_cast<const NodeMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:masterSlaveRPC.NodeMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_nodename().empty()) {
    _this->_internal_set_nodename(from._internal_nodename());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NodeMessage::CopyFrom(const NodeMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:masterSlaveRPC.NodeMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NodeMessage::InternalSwap(NodeMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nodename_, &other->_impl_.nodename_, arena);
}

::google::protobuf::Metadata NodeMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Id::_Internal {
 public:
};

Id::Id(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:masterSlaveRPC.Id)
}
Id::Id(
    ::google::protobuf::Arena* arena, const Id& from)
    : Id(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Id::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Id::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, taskid_),
           0,
           offsetof(Impl_, jobid_) -
               offsetof(Impl_, taskid_) +
               sizeof(Impl_::jobid_));
}
Id::~Id() {
  // @@protoc_insertion_point(destructor:masterSlaveRPC.Id)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Id::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Id::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Id, _impl_._cached_size_),
              false,
          },
          &Id::MergeImpl,
          &Id::kDescriptorMethods,
          &descriptor_table_rpc_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Id::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Id_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::masterSlaveRPC::Id>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 jobId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Id, _impl_.jobid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Id, _impl_.jobid_)}},
    // uint32 taskId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Id, _impl_.taskid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Id, _impl_.taskid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 taskId = 1;
    {PROTOBUF_FIELD_OFFSET(Id, _impl_.taskid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 jobId = 2;
    {PROTOBUF_FIELD_OFFSET(Id, _impl_.jobid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Id::Clear() {
// @@protoc_insertion_point(message_clear_start:masterSlaveRPC.Id)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.taskid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.jobid_) -
      reinterpret_cast<char*>(&_impl_.taskid_)) + sizeof(_impl_.jobid_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Id::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:masterSlaveRPC.Id)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 taskId = 1;
  if (this->_internal_taskid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_taskid(), target);
  }

  // uint32 jobId = 2;
  if (this->_internal_jobid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_jobid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:masterSlaveRPC.Id)
  return target;
}

::size_t Id::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:masterSlaveRPC.Id)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // uint32 taskId = 1;
  if (this->_internal_taskid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_taskid());
  }

  // uint32 jobId = 2;
  if (this->_internal_jobid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_jobid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Id::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Id*>(&to_msg);
  auto& from = static_cast<const Id&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:masterSlaveRPC.Id)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_taskid() != 0) {
    _this->_impl_.taskid_ = from._impl_.taskid_;
  }
  if (from._internal_jobid() != 0) {
    _this->_impl_.jobid_ = from._impl_.jobid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Id::CopyFrom(const Id& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:masterSlaveRPC.Id)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Id::InternalSwap(Id* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Id, _impl_.jobid_)
      + sizeof(Id::_impl_.jobid_)
      - PROTOBUF_FIELD_OFFSET(Id, _impl_.taskid_)>(
          reinterpret_cast<char*>(&_impl_.taskid_),
          reinterpret_cast<char*>(&other->_impl_.taskid_));
}

::google::protobuf::Metadata Id::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class JobMessage::_Internal {
 public:
  using HasBits =
      decltype(std::declval<JobMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(JobMessage, _impl_._has_bits_);
};

JobMessage::JobMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:masterSlaveRPC.JobMessage)
}
inline PROTOBUF_NDEBUG_INLINE JobMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::masterSlaveRPC::JobMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        key_(arena, from.key_),
        value_(arena, from.value_) {}

JobMessage::JobMessage(
    ::google::protobuf::Arena* arena,
    const JobMessage& from)
    : ::google::protobuf::Message(arena) {
  JobMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.id_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::masterSlaveRPC::Id>(
                              arena, *from._impl_.id_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, type_),
           offsetof(Impl_, jobnum_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::jobnum_));

  // @@protoc_insertion_point(copy_constructor:masterSlaveRPC.JobMessage)
}
inline PROTOBUF_NDEBUG_INLINE JobMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        key_(arena),
        value_(arena) {}

inline void JobMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, jobnum_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::jobnum_));
}
JobMessage::~JobMessage() {
  // @@protoc_insertion_point(destructor:masterSlaveRPC.JobMessage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void JobMessage::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.key_.Destroy();
  _impl_.value_.Destroy();
  delete _impl_.id_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
JobMessage::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(JobMessage, _impl_._cached_size_),
              false,
          },
          &JobMessage::MergeImpl,
          &JobMessage::kDescriptorMethods,
          &descriptor_table_rpc_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 1, 42, 2> JobMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JobMessage, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_JobMessage_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::masterSlaveRPC::JobMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .masterSlaveRPC.TaskType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(JobMessage, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.type_)}},
    // string key = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.key_)}},
    // string value = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.value_)}},
    // .masterSlaveRPC.Id id = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 0, 0, PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.id_)}},
    // uint32 jobnum = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(JobMessage, _impl_.jobnum_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.jobnum_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .masterSlaveRPC.TaskType type = 1;
    {PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string key = 2;
    {PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string value = 3;
    {PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .masterSlaveRPC.Id id = 4;
    {PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint32 jobnum = 5;
    {PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.jobnum_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::masterSlaveRPC::Id>()},
  }}, {{
    "\31\0\3\5\0\0\0\0"
    "masterSlaveRPC.JobMessage"
    "key"
    "value"
  }},
};

PROTOBUF_NOINLINE void JobMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:masterSlaveRPC.JobMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.key_.ClearToEmpty();
  _impl_.value_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.id_ != nullptr);
    _impl_.id_->Clear();
  }
  ::memset(&_impl_.type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.jobnum_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.jobnum_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* JobMessage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:masterSlaveRPC.JobMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .masterSlaveRPC.TaskType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_type(), target);
  }

  // string key = 2;
  if (!this->_internal_key().empty()) {
    const std::string& _s = this->_internal_key();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "masterSlaveRPC.JobMessage.key");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string value = 3;
  if (!this->_internal_value().empty()) {
    const std::string& _s = this->_internal_value();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "masterSlaveRPC.JobMessage.value");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .masterSlaveRPC.Id id = 4;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *_impl_.id_, _impl_.id_->GetCachedSize(), target, stream);
  }

  // uint32 jobnum = 5;
  if (this->_internal_jobnum() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this->_internal_jobnum(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:masterSlaveRPC.JobMessage)
  return target;
}

::size_t JobMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:masterSlaveRPC.JobMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string key = 2;
  if (!this->_internal_key().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_key());
  }

  // string value = 3;
  if (!this->_internal_value().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_value());
  }

  // .masterSlaveRPC.Id id = 4;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.id_);
  }

  // .masterSlaveRPC.TaskType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // uint32 jobnum = 5;
  if (this->_internal_jobnum() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_jobnum());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void JobMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<JobMessage*>(&to_msg);
  auto& from = static_cast<const JobMessage&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:masterSlaveRPC.JobMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.id_ != nullptr);
    if (_this->_impl_.id_ == nullptr) {
      _this->_impl_.id_ =
          ::google::protobuf::Message::CopyConstruct<::masterSlaveRPC::Id>(arena, *from._impl_.id_);
    } else {
      _this->_impl_.id_->MergeFrom(*from._impl_.id_);
    }
  }
  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  if (from._internal_jobnum() != 0) {
    _this->_impl_.jobnum_ = from._impl_.jobnum_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JobMessage::CopyFrom(const JobMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:masterSlaveRPC.JobMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void JobMessage::InternalSwap(JobMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.jobnum_)
      + sizeof(JobMessage::_impl_.jobnum_)
      - PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata JobMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MapDataList::_Internal {
 public:
};

MapDataList::MapDataList(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:masterSlaveRPC.MapDataList)
}
inline PROTOBUF_NDEBUG_INLINE MapDataList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::masterSlaveRPC::MapDataList& from_msg)
      : filename_{visibility, arena, from.filename_},
        _cached_size_{0} {}

MapDataList::MapDataList(
    ::google::protobuf::Arena* arena,
    const MapDataList& from)
    : ::google::protobuf::Message(arena) {
  MapDataList* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:masterSlaveRPC.MapDataList)
}
inline PROTOBUF_NDEBUG_INLINE MapDataList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filename_{visibility, arena},
        _cached_size_{0} {}

inline void MapDataList::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MapDataList::~MapDataList() {
  // @@protoc_insertion_point(destructor:masterSlaveRPC.MapDataList)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MapDataList::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
MapDataList::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(MapDataList, _impl_._cached_size_),
              false,
          },
          &MapDataList::MergeImpl,
          &MapDataList::kDescriptorMethods,
          &descriptor_table_rpc_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 43, 2> MapDataList::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MapDataList_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::masterSlaveRPC::MapDataList>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string filename = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MapDataList, _impl_.filename_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string filename = 1;
    {PROTOBUF_FIELD_OFFSET(MapDataList, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\32\10\0\0\0\0\0\0"
    "masterSlaveRPC.MapDataList"
    "filename"
  }},
};

PROTOBUF_NOINLINE void MapDataList::Clear() {
// @@protoc_insertion_point(message_clear_start:masterSlaveRPC.MapDataList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* MapDataList::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:masterSlaveRPC.MapDataList)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated string filename = 1;
  for (int i = 0, n = this->_internal_filename_size(); i < n; ++i) {
    const auto& s = this->_internal_filename().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "masterSlaveRPC.MapDataList.filename");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:masterSlaveRPC.MapDataList)
  return target;
}

::size_t MapDataList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:masterSlaveRPC.MapDataList)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated string filename = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_filename().size());
  for (int i = 0, n = _internal_filename().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_filename().Get(i));
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void MapDataList::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MapDataList*>(&to_msg);
  auto& from = static_cast<const MapDataList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:masterSlaveRPC.MapDataList)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_filename()->MergeFrom(from._internal_filename());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MapDataList::CopyFrom(const MapDataList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:masterSlaveRPC.MapDataList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MapDataList::InternalSwap(MapDataList* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.filename_.InternalSwap(&other->_impl_.filename_);
}

::google::protobuf::Metadata MapDataList::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EventMessage::_Internal {
 public:
};

EventMessage::EventMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:masterSlaveRPC.EventMessage)
}
EventMessage::EventMessage(
    ::google::protobuf::Arena* arena,
    const EventMessage& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  EventMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:masterSlaveRPC.EventMessage)
}

const ::google::protobuf::MessageLite::ClassData*
EventMessage::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(EventMessage, _impl_._cached_size_),
              false,
          },
          &EventMessage::MergeImpl,
          &EventMessage::kDescriptorMethods,
          &descriptor_table_rpc_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> EventMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_EventMessage_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::masterSlaveRPC::EventMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};









::google::protobuf::Metadata EventMessage::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace masterSlaveRPC
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_rpc_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
