// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpc.proto
// Protobuf C++ Version: 5.27.2

#include "rpc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace masterSlaveRPC {

inline constexpr NodeMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : nodename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NodeMessage::NodeMessage(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct NodeMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NodeMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NodeMessageDefaultTypeInternal() {}
  union {
    NodeMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NodeMessageDefaultTypeInternal _NodeMessage_default_instance_;

inline constexpr MapDataList::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filename_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MapDataList::MapDataList(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MapDataListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MapDataListDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MapDataListDefaultTypeInternal() {}
  union {
    MapDataList _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MapDataListDefaultTypeInternal _MapDataList_default_instance_;

inline constexpr JobMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_{static_cast< ::masterSlaveRPC::JobMessage_TaskType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR JobMessage::JobMessage(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct JobMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JobMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JobMessageDefaultTypeInternal() {}
  union {
    JobMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JobMessageDefaultTypeInternal _JobMessage_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR EventMessage::EventMessage(::_pbi::ConstantInitialized) {}
struct EventMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventMessageDefaultTypeInternal() {}
  union {
    EventMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventMessageDefaultTypeInternal _EventMessage_default_instance_;
}  // namespace masterSlaveRPC
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_rpc_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_rpc_2eproto = nullptr;
const ::uint32_t
    TableStruct_rpc_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::NodeMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::NodeMessage, _impl_.nodename_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::JobMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::JobMessage, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::JobMessage, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::JobMessage, _impl_.value_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::MapDataList, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::MapDataList, _impl_.filename_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::masterSlaveRPC::EventMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::masterSlaveRPC::NodeMessage)},
        {9, -1, -1, sizeof(::masterSlaveRPC::JobMessage)},
        {20, -1, -1, sizeof(::masterSlaveRPC::MapDataList)},
        {29, -1, -1, sizeof(::masterSlaveRPC::EventMessage)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::masterSlaveRPC::_NodeMessage_default_instance_._instance,
    &::masterSlaveRPC::_JobMessage_default_instance_._instance,
    &::masterSlaveRPC::_MapDataList_default_instance_._instance,
    &::masterSlaveRPC::_EventMessage_default_instance_._instance,
};
const char descriptor_table_protodef_rpc_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\trpc.proto\022\016masterSlaveRPC\032\033google/prot"
    "obuf/empty.proto\"\037\n\013NodeMessage\022\020\n\010nodeN"
    "ame\030\001 \001(\t\"\207\001\n\nJobMessage\0221\n\004type\030\001 \001(\0162#"
    ".masterSlaveRPC.JobMessage.TaskType\022\013\n\003k"
    "ey\030\002 \001(\t\022\r\n\005value\030\003 \001(\t\"*\n\010TaskType\022\007\n\003m"
    "ap\020\000\022\n\n\006reduce\020\001\022\t\n\005fetch\020\002\"\037\n\013MapDataLi"
    "st\022\020\n\010filename\030\001 \003(\t\"\016\n\014EventMessage2\262\002\n"
    "\006JobRpc\022G\n\nRequireJob\022\033.masterSlaveRPC.N"
    "odeMessage\032\032.masterSlaveRPC.JobMessage\"\000"
    "\022N\n\020FetchDataFromMap\022\033.masterSlaveRPC.No"
    "deMessage\032\033.masterSlaveRPC.MapDataList\"\000"
    "\022H\n\017ReportJobStatus\022\033.masterSlaveRPC.Nod"
    "eMessage\032\026.google.protobuf.Empty\"\000\022E\n\013Re"
    "portEvent\022\034.masterSlaveRPC.EventMessage\032"
    "\026.google.protobuf.Empty\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_rpc_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_rpc_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rpc_2eproto = {
    false,
    false,
    593,
    descriptor_table_protodef_rpc_2eproto,
    "rpc.proto",
    &descriptor_table_rpc_2eproto_once,
    descriptor_table_rpc_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_rpc_2eproto::offsets,
    file_level_enum_descriptors_rpc_2eproto,
    file_level_service_descriptors_rpc_2eproto,
};
namespace masterSlaveRPC {
const ::google::protobuf::EnumDescriptor* JobMessage_TaskType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_rpc_2eproto);
  return file_level_enum_descriptors_rpc_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t JobMessage_TaskType_internal_data_[] = {
    196608u, 0u, };
bool JobMessage_TaskType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr JobMessage_TaskType JobMessage::map;
constexpr JobMessage_TaskType JobMessage::reduce;
constexpr JobMessage_TaskType JobMessage::fetch;
constexpr JobMessage_TaskType JobMessage::TaskType_MIN;
constexpr JobMessage_TaskType JobMessage::TaskType_MAX;
constexpr int JobMessage::TaskType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class NodeMessage::_Internal {
 public:
};

NodeMessage::NodeMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:masterSlaveRPC.NodeMessage)
}
inline PROTOBUF_NDEBUG_INLINE NodeMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::masterSlaveRPC::NodeMessage& from_msg)
      : nodename_(arena, from.nodename_),
        _cached_size_{0} {}

NodeMessage::NodeMessage(
    ::google::protobuf::Arena* arena,
    const NodeMessage& from)
    : ::google::protobuf::Message(arena) {
  NodeMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:masterSlaveRPC.NodeMessage)
}
inline PROTOBUF_NDEBUG_INLINE NodeMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : nodename_(arena),
        _cached_size_{0} {}

inline void NodeMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
NodeMessage::~NodeMessage() {
  // @@protoc_insertion_point(destructor:masterSlaveRPC.NodeMessage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NodeMessage::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.nodename_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
NodeMessage::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(NodeMessage, _impl_._cached_size_),
              false,
          },
          &NodeMessage::MergeImpl,
          &NodeMessage::kDescriptorMethods,
          &descriptor_table_rpc_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 43, 2> NodeMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_NodeMessage_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::masterSlaveRPC::NodeMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string nodeName = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NodeMessage, _impl_.nodename_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string nodeName = 1;
    {PROTOBUF_FIELD_OFFSET(NodeMessage, _impl_.nodename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\10\0\0\0\0\0\0"
    "masterSlaveRPC.NodeMessage"
    "nodeName"
  }},
};

PROTOBUF_NOINLINE void NodeMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:masterSlaveRPC.NodeMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nodename_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* NodeMessage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:masterSlaveRPC.NodeMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string nodeName = 1;
  if (!this->_internal_nodename().empty()) {
    const std::string& _s = this->_internal_nodename();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "masterSlaveRPC.NodeMessage.nodeName");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:masterSlaveRPC.NodeMessage)
  return target;
}

::size_t NodeMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:masterSlaveRPC.NodeMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string nodeName = 1;
  if (!this->_internal_nodename().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_nodename());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void NodeMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NodeMessage*>(&to_msg);
  auto& from = static_cast<const NodeMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:masterSlaveRPC.NodeMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_nodename().empty()) {
    _this->_internal_set_nodename(from._internal_nodename());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NodeMessage::CopyFrom(const NodeMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:masterSlaveRPC.NodeMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NodeMessage::InternalSwap(NodeMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nodename_, &other->_impl_.nodename_, arena);
}

::google::protobuf::Metadata NodeMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class JobMessage::_Internal {
 public:
};

JobMessage::JobMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:masterSlaveRPC.JobMessage)
}
inline PROTOBUF_NDEBUG_INLINE JobMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::masterSlaveRPC::JobMessage& from_msg)
      : key_(arena, from.key_),
        value_(arena, from.value_),
        _cached_size_{0} {}

JobMessage::JobMessage(
    ::google::protobuf::Arena* arena,
    const JobMessage& from)
    : ::google::protobuf::Message(arena) {
  JobMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.type_ = from._impl_.type_;

  // @@protoc_insertion_point(copy_constructor:masterSlaveRPC.JobMessage)
}
inline PROTOBUF_NDEBUG_INLINE JobMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : key_(arena),
        value_(arena),
        _cached_size_{0} {}

inline void JobMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.type_ = {};
}
JobMessage::~JobMessage() {
  // @@protoc_insertion_point(destructor:masterSlaveRPC.JobMessage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void JobMessage::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.key_.Destroy();
  _impl_.value_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
JobMessage::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(JobMessage, _impl_._cached_size_),
              false,
          },
          &JobMessage::MergeImpl,
          &JobMessage::kDescriptorMethods,
          &descriptor_table_rpc_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 42, 2> JobMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_JobMessage_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::masterSlaveRPC::JobMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .masterSlaveRPC.JobMessage.TaskType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(JobMessage, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.type_)}},
    // string key = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.key_)}},
    // string value = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .masterSlaveRPC.JobMessage.TaskType type = 1;
    {PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string key = 2;
    {PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.key_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string value = 3;
    {PROTOBUF_FIELD_OFFSET(JobMessage, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\0\3\5\0\0\0\0"
    "masterSlaveRPC.JobMessage"
    "key"
    "value"
  }},
};

PROTOBUF_NOINLINE void JobMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:masterSlaveRPC.JobMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.key_.ClearToEmpty();
  _impl_.value_.ClearToEmpty();
  _impl_.type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* JobMessage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:masterSlaveRPC.JobMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .masterSlaveRPC.JobMessage.TaskType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_type(), target);
  }

  // string key = 2;
  if (!this->_internal_key().empty()) {
    const std::string& _s = this->_internal_key();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "masterSlaveRPC.JobMessage.key");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string value = 3;
  if (!this->_internal_value().empty()) {
    const std::string& _s = this->_internal_value();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "masterSlaveRPC.JobMessage.value");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:masterSlaveRPC.JobMessage)
  return target;
}

::size_t JobMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:masterSlaveRPC.JobMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string key = 2;
  if (!this->_internal_key().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_key());
  }

  // string value = 3;
  if (!this->_internal_value().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_value());
  }

  // .masterSlaveRPC.JobMessage.TaskType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void JobMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<JobMessage*>(&to_msg);
  auto& from = static_cast<const JobMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:masterSlaveRPC.JobMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JobMessage::CopyFrom(const JobMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:masterSlaveRPC.JobMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void JobMessage::InternalSwap(JobMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
  swap(_impl_.type_, other->_impl_.type_);
}

::google::protobuf::Metadata JobMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MapDataList::_Internal {
 public:
};

MapDataList::MapDataList(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:masterSlaveRPC.MapDataList)
}
inline PROTOBUF_NDEBUG_INLINE MapDataList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::masterSlaveRPC::MapDataList& from_msg)
      : filename_{visibility, arena, from.filename_},
        _cached_size_{0} {}

MapDataList::MapDataList(
    ::google::protobuf::Arena* arena,
    const MapDataList& from)
    : ::google::protobuf::Message(arena) {
  MapDataList* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:masterSlaveRPC.MapDataList)
}
inline PROTOBUF_NDEBUG_INLINE MapDataList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filename_{visibility, arena},
        _cached_size_{0} {}

inline void MapDataList::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MapDataList::~MapDataList() {
  // @@protoc_insertion_point(destructor:masterSlaveRPC.MapDataList)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MapDataList::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
MapDataList::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(MapDataList, _impl_._cached_size_),
              false,
          },
          &MapDataList::MergeImpl,
          &MapDataList::kDescriptorMethods,
          &descriptor_table_rpc_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 43, 2> MapDataList::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MapDataList_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::masterSlaveRPC::MapDataList>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string filename = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MapDataList, _impl_.filename_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string filename = 1;
    {PROTOBUF_FIELD_OFFSET(MapDataList, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\32\10\0\0\0\0\0\0"
    "masterSlaveRPC.MapDataList"
    "filename"
  }},
};

PROTOBUF_NOINLINE void MapDataList::Clear() {
// @@protoc_insertion_point(message_clear_start:masterSlaveRPC.MapDataList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* MapDataList::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:masterSlaveRPC.MapDataList)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated string filename = 1;
  for (int i = 0, n = this->_internal_filename_size(); i < n; ++i) {
    const auto& s = this->_internal_filename().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "masterSlaveRPC.MapDataList.filename");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:masterSlaveRPC.MapDataList)
  return target;
}

::size_t MapDataList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:masterSlaveRPC.MapDataList)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated string filename = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_filename().size());
  for (int i = 0, n = _internal_filename().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_filename().Get(i));
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void MapDataList::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MapDataList*>(&to_msg);
  auto& from = static_cast<const MapDataList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:masterSlaveRPC.MapDataList)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_filename()->MergeFrom(from._internal_filename());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MapDataList::CopyFrom(const MapDataList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:masterSlaveRPC.MapDataList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MapDataList::InternalSwap(MapDataList* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.filename_.InternalSwap(&other->_impl_.filename_);
}

::google::protobuf::Metadata MapDataList::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EventMessage::_Internal {
 public:
};

EventMessage::EventMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:masterSlaveRPC.EventMessage)
}
EventMessage::EventMessage(
    ::google::protobuf::Arena* arena,
    const EventMessage& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  EventMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:masterSlaveRPC.EventMessage)
}

const ::google::protobuf::MessageLite::ClassData*
EventMessage::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(EventMessage, _impl_._cached_size_),
              false,
          },
          &EventMessage::MergeImpl,
          &EventMessage::kDescriptorMethods,
          &descriptor_table_rpc_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> EventMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_EventMessage_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::masterSlaveRPC::EventMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};









::google::protobuf::Metadata EventMessage::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace masterSlaveRPC
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_rpc_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
