// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mr.proto
// Protobuf C++ Version: 5.27.2

#include "mr.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace MapReduce {

inline constexpr Reply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        tasktype_{static_cast< ::MapReduce::TaskType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Reply::Reply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReplyDefaultTypeInternal() {}
  union {
    Reply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReplyDefaultTypeInternal _Reply_default_instance_;

inline constexpr NodeMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : isbusy_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NodeMessage::NodeMessage(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct NodeMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NodeMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NodeMessageDefaultTypeInternal() {}
  union {
    NodeMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NodeMessageDefaultTypeInternal _NodeMessage_default_instance_;

inline constexpr HeartBeatReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : receive_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR HeartBeatReply::HeartBeatReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct HeartBeatReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartBeatReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartBeatReplyDefaultTypeInternal() {}
  union {
    HeartBeatReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartBeatReplyDefaultTypeInternal _HeartBeatReply_default_instance_;

inline constexpr HeartBeatMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : hostname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR HeartBeatMsg::HeartBeatMsg(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct HeartBeatMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartBeatMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartBeatMsgDefaultTypeInternal() {}
  union {
    HeartBeatMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartBeatMsgDefaultTypeInternal _HeartBeatMsg_default_instance_;

inline constexpr FinishMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        tasktype_{static_cast< ::MapReduce::TaskType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FinishMsg::FinishMsg(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FinishMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FinishMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FinishMsgDefaultTypeInternal() {}
  union {
    FinishMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FinishMsgDefaultTypeInternal _FinishMsg_default_instance_;
}  // namespace MapReduce
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_mr_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_mr_2eproto = nullptr;
const ::uint32_t
    TableStruct_mr_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MapReduce::NodeMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MapReduce::NodeMessage, _impl_.isbusy_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MapReduce::Reply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MapReduce::Reply, _impl_.tasktype_),
        PROTOBUF_FIELD_OFFSET(::MapReduce::Reply, _impl_.filename_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MapReduce::FinishMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MapReduce::FinishMsg, _impl_.tasktype_),
        PROTOBUF_FIELD_OFFSET(::MapReduce::FinishMsg, _impl_.filename_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MapReduce::HeartBeatMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MapReduce::HeartBeatMsg, _impl_.hostname_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MapReduce::HeartBeatReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MapReduce::HeartBeatReply, _impl_.receive_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::MapReduce::NodeMessage)},
        {9, -1, -1, sizeof(::MapReduce::Reply)},
        {19, -1, -1, sizeof(::MapReduce::FinishMsg)},
        {29, -1, -1, sizeof(::MapReduce::HeartBeatMsg)},
        {38, -1, -1, sizeof(::MapReduce::HeartBeatReply)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::MapReduce::_NodeMessage_default_instance_._instance,
    &::MapReduce::_Reply_default_instance_._instance,
    &::MapReduce::_FinishMsg_default_instance_._instance,
    &::MapReduce::_HeartBeatMsg_default_instance_._instance,
    &::MapReduce::_HeartBeatReply_default_instance_._instance,
};
const char descriptor_table_protodef_mr_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\010mr.proto\022\tMapReduce\032\033google/protobuf/e"
    "mpty.proto\"\035\n\013NodeMessage\022\016\n\006isBusy\030\001 \001("
    "\010\"@\n\005Reply\022%\n\010taskType\030\001 \001(\0162\023.MapReduce"
    ".TaskType\022\020\n\010fileName\030\002 \001(\t\"D\n\tFinishMsg"
    "\022%\n\010taskType\030\001 \001(\0162\023.MapReduce.TaskType\022"
    "\020\n\010fileName\030\002 \001(\t\" \n\014HeartBeatMsg\022\020\n\010hos"
    "tname\030\001 \001(\t\"!\n\016HeartBeatReply\022\017\n\007receive"
    "\030\001 \001(\010*\037\n\010TaskType\022\007\n\003map\020\000\022\n\n\006reduce\020\0012"
    "}\n\nRequireJob\0225\n\007Require\022\026.MapReduce.Nod"
    "eMessage\032\020.MapReduce.Reply\"\000\0228\n\006Finish\022\024"
    ".MapReduce.FinishMsg\032\026.google.protobuf.E"
    "mpty\"\0002R\n\tHeartBeat\022E\n\rSendHeartBeat\022\027.M"
    "apReduce.HeartBeatMsg\032\031.MapReduce.HeartB"
    "eatReply\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_mr_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_mr_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_mr_2eproto = {
    false,
    false,
    538,
    descriptor_table_protodef_mr_2eproto,
    "mr.proto",
    &descriptor_table_mr_2eproto_once,
    descriptor_table_mr_2eproto_deps,
    1,
    5,
    schemas,
    file_default_instances,
    TableStruct_mr_2eproto::offsets,
    file_level_enum_descriptors_mr_2eproto,
    file_level_service_descriptors_mr_2eproto,
};
namespace MapReduce {
const ::google::protobuf::EnumDescriptor* TaskType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_mr_2eproto);
  return file_level_enum_descriptors_mr_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t TaskType_internal_data_[] = {
    131072u, 0u, };
bool TaskType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// ===================================================================

class NodeMessage::_Internal {
 public:
};

NodeMessage::NodeMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MapReduce.NodeMessage)
}
NodeMessage::NodeMessage(
    ::google::protobuf::Arena* arena, const NodeMessage& from)
    : NodeMessage(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE NodeMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void NodeMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.isbusy_ = {};
}
NodeMessage::~NodeMessage() {
  // @@protoc_insertion_point(destructor:MapReduce.NodeMessage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NodeMessage::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
NodeMessage::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(NodeMessage, _impl_._cached_size_),
              false,
          },
          &NodeMessage::MergeImpl,
          &NodeMessage::kDescriptorMethods,
          &descriptor_table_mr_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> NodeMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_NodeMessage_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MapReduce::NodeMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool isBusy = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NodeMessage, _impl_.isbusy_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(NodeMessage, _impl_.isbusy_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool isBusy = 1;
    {PROTOBUF_FIELD_OFFSET(NodeMessage, _impl_.isbusy_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void NodeMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:MapReduce.NodeMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.isbusy_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* NodeMessage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MapReduce.NodeMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool isBusy = 1;
  if (this->_internal_isbusy() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_isbusy(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MapReduce.NodeMessage)
  return target;
}

::size_t NodeMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MapReduce.NodeMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool isBusy = 1;
  if (this->_internal_isbusy() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void NodeMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NodeMessage*>(&to_msg);
  auto& from = static_cast<const NodeMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MapReduce.NodeMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_isbusy() != 0) {
    _this->_impl_.isbusy_ = from._impl_.isbusy_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NodeMessage::CopyFrom(const NodeMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MapReduce.NodeMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NodeMessage::InternalSwap(NodeMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.isbusy_, other->_impl_.isbusy_);
}

::google::protobuf::Metadata NodeMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Reply::_Internal {
 public:
};

Reply::Reply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MapReduce.Reply)
}
inline PROTOBUF_NDEBUG_INLINE Reply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MapReduce::Reply& from_msg)
      : filename_(arena, from.filename_),
        _cached_size_{0} {}

Reply::Reply(
    ::google::protobuf::Arena* arena,
    const Reply& from)
    : ::google::protobuf::Message(arena) {
  Reply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.tasktype_ = from._impl_.tasktype_;

  // @@protoc_insertion_point(copy_constructor:MapReduce.Reply)
}
inline PROTOBUF_NDEBUG_INLINE Reply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filename_(arena),
        _cached_size_{0} {}

inline void Reply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.tasktype_ = {};
}
Reply::~Reply() {
  // @@protoc_insertion_point(destructor:MapReduce.Reply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Reply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.filename_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Reply::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Reply, _impl_._cached_size_),
              false,
          },
          &Reply::MergeImpl,
          &Reply::kDescriptorMethods,
          &descriptor_table_mr_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 32, 2> Reply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Reply_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MapReduce::Reply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string fileName = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Reply, _impl_.filename_)}},
    // .MapReduce.TaskType taskType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Reply, _impl_.tasktype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Reply, _impl_.tasktype_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .MapReduce.TaskType taskType = 1;
    {PROTOBUF_FIELD_OFFSET(Reply, _impl_.tasktype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string fileName = 2;
    {PROTOBUF_FIELD_OFFSET(Reply, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\17\0\10\0\0\0\0\0"
    "MapReduce.Reply"
    "fileName"
  }},
};

PROTOBUF_NOINLINE void Reply::Clear() {
// @@protoc_insertion_point(message_clear_start:MapReduce.Reply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.ClearToEmpty();
  _impl_.tasktype_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Reply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MapReduce.Reply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .MapReduce.TaskType taskType = 1;
  if (this->_internal_tasktype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_tasktype(), target);
  }

  // string fileName = 2;
  if (!this->_internal_filename().empty()) {
    const std::string& _s = this->_internal_filename();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MapReduce.Reply.fileName");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MapReduce.Reply)
  return target;
}

::size_t Reply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MapReduce.Reply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string fileName = 2;
  if (!this->_internal_filename().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_filename());
  }

  // .MapReduce.TaskType taskType = 1;
  if (this->_internal_tasktype() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_tasktype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Reply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Reply*>(&to_msg);
  auto& from = static_cast<const Reply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MapReduce.Reply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (from._internal_tasktype() != 0) {
    _this->_impl_.tasktype_ = from._impl_.tasktype_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Reply::CopyFrom(const Reply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MapReduce.Reply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Reply::InternalSwap(Reply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  swap(_impl_.tasktype_, other->_impl_.tasktype_);
}

::google::protobuf::Metadata Reply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FinishMsg::_Internal {
 public:
};

FinishMsg::FinishMsg(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MapReduce.FinishMsg)
}
inline PROTOBUF_NDEBUG_INLINE FinishMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MapReduce::FinishMsg& from_msg)
      : filename_(arena, from.filename_),
        _cached_size_{0} {}

FinishMsg::FinishMsg(
    ::google::protobuf::Arena* arena,
    const FinishMsg& from)
    : ::google::protobuf::Message(arena) {
  FinishMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.tasktype_ = from._impl_.tasktype_;

  // @@protoc_insertion_point(copy_constructor:MapReduce.FinishMsg)
}
inline PROTOBUF_NDEBUG_INLINE FinishMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filename_(arena),
        _cached_size_{0} {}

inline void FinishMsg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.tasktype_ = {};
}
FinishMsg::~FinishMsg() {
  // @@protoc_insertion_point(destructor:MapReduce.FinishMsg)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FinishMsg::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.filename_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
FinishMsg::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(FinishMsg, _impl_._cached_size_),
              false,
          },
          &FinishMsg::MergeImpl,
          &FinishMsg::kDescriptorMethods,
          &descriptor_table_mr_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 36, 2> FinishMsg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FinishMsg_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MapReduce::FinishMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string fileName = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(FinishMsg, _impl_.filename_)}},
    // .MapReduce.TaskType taskType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FinishMsg, _impl_.tasktype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(FinishMsg, _impl_.tasktype_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .MapReduce.TaskType taskType = 1;
    {PROTOBUF_FIELD_OFFSET(FinishMsg, _impl_.tasktype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string fileName = 2;
    {PROTOBUF_FIELD_OFFSET(FinishMsg, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\0\10\0\0\0\0\0"
    "MapReduce.FinishMsg"
    "fileName"
  }},
};

PROTOBUF_NOINLINE void FinishMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:MapReduce.FinishMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.ClearToEmpty();
  _impl_.tasktype_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* FinishMsg::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MapReduce.FinishMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .MapReduce.TaskType taskType = 1;
  if (this->_internal_tasktype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_tasktype(), target);
  }

  // string fileName = 2;
  if (!this->_internal_filename().empty()) {
    const std::string& _s = this->_internal_filename();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MapReduce.FinishMsg.fileName");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MapReduce.FinishMsg)
  return target;
}

::size_t FinishMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MapReduce.FinishMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string fileName = 2;
  if (!this->_internal_filename().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_filename());
  }

  // .MapReduce.TaskType taskType = 1;
  if (this->_internal_tasktype() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_tasktype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void FinishMsg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FinishMsg*>(&to_msg);
  auto& from = static_cast<const FinishMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MapReduce.FinishMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (from._internal_tasktype() != 0) {
    _this->_impl_.tasktype_ = from._impl_.tasktype_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FinishMsg::CopyFrom(const FinishMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MapReduce.FinishMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FinishMsg::InternalSwap(FinishMsg* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  swap(_impl_.tasktype_, other->_impl_.tasktype_);
}

::google::protobuf::Metadata FinishMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class HeartBeatMsg::_Internal {
 public:
};

HeartBeatMsg::HeartBeatMsg(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MapReduce.HeartBeatMsg)
}
inline PROTOBUF_NDEBUG_INLINE HeartBeatMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MapReduce::HeartBeatMsg& from_msg)
      : hostname_(arena, from.hostname_),
        _cached_size_{0} {}

HeartBeatMsg::HeartBeatMsg(
    ::google::protobuf::Arena* arena,
    const HeartBeatMsg& from)
    : ::google::protobuf::Message(arena) {
  HeartBeatMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:MapReduce.HeartBeatMsg)
}
inline PROTOBUF_NDEBUG_INLINE HeartBeatMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : hostname_(arena),
        _cached_size_{0} {}

inline void HeartBeatMsg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
HeartBeatMsg::~HeartBeatMsg() {
  // @@protoc_insertion_point(destructor:MapReduce.HeartBeatMsg)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void HeartBeatMsg::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.hostname_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
HeartBeatMsg::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(HeartBeatMsg, _impl_._cached_size_),
              false,
          },
          &HeartBeatMsg::MergeImpl,
          &HeartBeatMsg::kDescriptorMethods,
          &descriptor_table_mr_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 39, 2> HeartBeatMsg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_HeartBeatMsg_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MapReduce::HeartBeatMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string hostname = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(HeartBeatMsg, _impl_.hostname_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string hostname = 1;
    {PROTOBUF_FIELD_OFFSET(HeartBeatMsg, _impl_.hostname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\10\0\0\0\0\0\0"
    "MapReduce.HeartBeatMsg"
    "hostname"
  }},
};

PROTOBUF_NOINLINE void HeartBeatMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:MapReduce.HeartBeatMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.hostname_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* HeartBeatMsg::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MapReduce.HeartBeatMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string hostname = 1;
  if (!this->_internal_hostname().empty()) {
    const std::string& _s = this->_internal_hostname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MapReduce.HeartBeatMsg.hostname");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MapReduce.HeartBeatMsg)
  return target;
}

::size_t HeartBeatMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MapReduce.HeartBeatMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string hostname = 1;
  if (!this->_internal_hostname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_hostname());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void HeartBeatMsg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<HeartBeatMsg*>(&to_msg);
  auto& from = static_cast<const HeartBeatMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MapReduce.HeartBeatMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_hostname().empty()) {
    _this->_internal_set_hostname(from._internal_hostname());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HeartBeatMsg::CopyFrom(const HeartBeatMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MapReduce.HeartBeatMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HeartBeatMsg::InternalSwap(HeartBeatMsg* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.hostname_, &other->_impl_.hostname_, arena);
}

::google::protobuf::Metadata HeartBeatMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class HeartBeatReply::_Internal {
 public:
};

HeartBeatReply::HeartBeatReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MapReduce.HeartBeatReply)
}
HeartBeatReply::HeartBeatReply(
    ::google::protobuf::Arena* arena, const HeartBeatReply& from)
    : HeartBeatReply(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE HeartBeatReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void HeartBeatReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.receive_ = {};
}
HeartBeatReply::~HeartBeatReply() {
  // @@protoc_insertion_point(destructor:MapReduce.HeartBeatReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void HeartBeatReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
HeartBeatReply::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(HeartBeatReply, _impl_._cached_size_),
              false,
          },
          &HeartBeatReply::MergeImpl,
          &HeartBeatReply::kDescriptorMethods,
          &descriptor_table_mr_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> HeartBeatReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_HeartBeatReply_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MapReduce::HeartBeatReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool receive = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(HeartBeatReply, _impl_.receive_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(HeartBeatReply, _impl_.receive_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool receive = 1;
    {PROTOBUF_FIELD_OFFSET(HeartBeatReply, _impl_.receive_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void HeartBeatReply::Clear() {
// @@protoc_insertion_point(message_clear_start:MapReduce.HeartBeatReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.receive_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* HeartBeatReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MapReduce.HeartBeatReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool receive = 1;
  if (this->_internal_receive() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_receive(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MapReduce.HeartBeatReply)
  return target;
}

::size_t HeartBeatReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MapReduce.HeartBeatReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool receive = 1;
  if (this->_internal_receive() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void HeartBeatReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<HeartBeatReply*>(&to_msg);
  auto& from = static_cast<const HeartBeatReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MapReduce.HeartBeatReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_receive() != 0) {
    _this->_impl_.receive_ = from._impl_.receive_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HeartBeatReply::CopyFrom(const HeartBeatReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MapReduce.HeartBeatReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HeartBeatReply::InternalSwap(HeartBeatReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.receive_, other->_impl_.receive_);
}

::google::protobuf::Metadata HeartBeatReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace MapReduce
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_mr_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
